image: Visual Studio 2017
configuration: Release  
branches:
  only:
    - master
clone_depth: 1

before_build:
  - nuget restore Nancy.Authentication.Jwt.sln
cache:
  - packages -> **\packages.config
build:
  project: Nancy.Authentication.Jwt.sln
  parallel: true
  verbosity: minimal

test: off
deploy: off
